name: 'Auto Assign PRs'
on:
  workflow_call:
  
  pull_request:
    types: [opened, ready_for_review]
    

jobs:
  add-reviews:
    name: Auto Assign
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.0
