name: JIRA Autolink Action
on:
  workflow_call:
  
  pull_request:
    types: [opened, ready_for_review]


jobs:
  link_ticket:
    name: Link Ticket
    runs-on: ubuntu-latest
    steps:
      - name: Clean title
        id: clean_title
        run: echo ::set-output name=title::$( echo ${{ github.event.pull_request.title }} | sed 's/[A-Za-z][A-Za-z]*\s*[\/-]*[0-9][0-9]*[\/-:]*//')
      - name: Check for Ticket
        id: check-for-ticket
        run: |
          if [[ ${{ github.head_ref }} =~ ^[A-Za-z]+-[0-9]+ ]]; then
              echo ::set-output name=match::true
          fi
      - uses: tzkhan/pr-update-action@v2
        if: steps.check-for-ticket.outputs.match == 'true'
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          title-update-action: 'replace'
          head-branch-regex: '^[A-Za-z]+-[0-9]+'
          title-template: '%headbranch%: ${{ steps.clean_title.outputs.title }}'
          body-template: |
            [JIRA Link: %headbranch%](https://flocasts.atlassian.net/browse/%headbranch%)
            ---
          body-update-action: 'prefix'
          body-uppercase-base-match: false
